<template>
  <div class="me-table">
    <div
      class="me-table-head"
      v-show="show"
      ref="search"
    >
      <me-search>
        <me-search-item
          v-for="(config, index) in searchConfig"
          :key="`${config.prop}_${config.label}_${index}`"
          v-bind="config"
        ></me-search-item>
      </me-search>
    </div>
    <div class="me-table-tool">
      <div>
        <slot name="operator" />
      </div>
      <div>
        <table-icon
          :content="show ? '隐藏搜索' : '展开搜索'"
          icon="el-icon-search"
          @click="changeSearchStatus"
        >
        </table-icon>
        <table-icon
          content="刷新"
          icon="el-icon-refresh"
          @click="refresh"
        >
        </table-icon>
      </div>
    </div>
    <el-table
      ref="table"
      :data="list"
      :height="tableHeight"
      style="width: 100%; height: 100%"
    >
      <slot />
    </el-table>
    <div class="me-table-footer">
      <div>
        <slot name="footer"></slot>
      </div>
      <div>1222</div>
    </div>
  </div>
</template>

<script>
import TableIcon from "./table-icon.vue"
import MeSearch from "../../search/src/search.vue"
import MeSearchItem from "../../search/src/search-item.vue"
export default {
  components: { TableIcon, MeSearch, MeSearchItem },
  name: "Table",
  data() {
    return {
      //是否展示搜索
      show: true,
      //搜索配置，根据slot生成
      searchConfig: [],
      //表格高度
      tableHeight: "auto",
      list: [
        {
          id: "1752607719296073730",
          name: "福建省电子信息（集团）有限责任公司",
          creditCode: "91350000717397615U",
          typeId: null,
          typeName: null,
          postalCode: "55555",
          profile: null,
          logo: null,
          logoUrl: null,
          creditUrl: null,
          contacts: "承租方Y",
          contactsPhone: null,
          contactsFax: null,
          registerDate: null,
          registerCapital: null,
          corpType: null,
          corpTypeName: null,
          provinceName: null,
          cityName: null,
          countiesName: null,
          provinceCode: null,
          cityCode: null,
          countiesCode: null,
          addr: null,
          legalPerson: null,
          legalPhone: null,
          remark: null,
          status: 0,
          customerTagline: null,
          customerUrl: null,
          email: null,
          product: null,
          deptId: "100",
          createUserId: "1717016875626741760",
          createDate: "2024-01-31 16:20:17",
          updateUserId: "1737780523903516672",
          updateDate: "2024-02-03 16:54:00",
          isDeleted: 0,
          statusStr: "正常",
          isExpired: true,
          rentalRoomNumbers: "S栋/2001、S栋/2002",
          purchaseRoomNumbers: null,
          rentalRoomIds: "1752594532026810369,1752594532039393281",
          purchaseRoomIds: null,
          totalContractCount: 0,
          expiredContractCount: 0,
          areaList: null,
          allAddress: null,
          contractStatus: null,
          contractStatusStr: null,
          updateUser: "jiaec02",
          settledType: "0",
          settledTypeStr: "租户",
          memberCount: 1,
          adminPhone: "13726295713",
          housingInformation: null,
          memberList: null,
          area: null,
          areaText: null,
          allRoomNumbers: "S栋/2001、S栋/2002",
        },
        {
          id: "1751078184100601858",
          name: "上海萌派文化传播有限公司",
          creditCode: "91310116MA1J8MLF68",
          typeId: null,
          typeName: null,
          postalCode: null,
          profile: null,
          logo: null,
          logoUrl: null,
          creditUrl: null,
          contacts: "Lyy",
          contactsPhone: null,
          contactsFax: null,
          registerDate: null,
          registerCapital: null,
          corpType: null,
          corpTypeName: null,
          provinceName: null,
          cityName: null,
          countiesName: null,
          provinceCode: null,
          cityCode: null,
          countiesCode: null,
          addr: null,
          legalPerson: null,
          legalPhone: null,
          remark: null,
          status: 0,
          customerTagline: null,
          customerUrl: null,
          email: null,
          product: null,
          deptId: "102",
          createUserId: "1748239418958553088",
          createDate: "2024-01-27 11:02:27",
          updateUserId: "1748239418958553088",
          updateDate: "2024-02-03 15:51:30",
          isDeleted: 0,
          statusStr: "正常",
          isExpired: true,
          rentalRoomNumbers: "10栋/1、13栋/1301-1、13栋/1301-2、2栋/1001、2栋/1002、5栋/309、88栋/1、CE栋/1208、DD栋/回归数据2、DD栋/回归数据3、DD栋/回归新数据1、K2栋/1003、K2栋/1006、K2栋/1007、S栋/2009、S栋/2010、S栋/2011、S栋/2012、S栋/808、测试租赁/101",
          purchaseRoomNumbers: null,
          rentalRoomIds: "1719284732790882306,1719894632424304641,1745017140869611522,1748228813805932546,1748291353512538114,1748312310784487426,1748312422059372545,1751127640229572610,1751148980437282818,1751149126852046849,1751149294657761281,1751149464602570753,1752593192345141",
          purchaseRoomIds: null,
          totalContractCount: 0,
          expiredContractCount: 0,
          areaList: null,
          allAddress: null,
          contractStatus: null,
          contractStatusStr: null,
          updateUser: "梁咏茵09",
          settledType: "0",
          settledTypeStr: "租户",
          memberCount: 3,
          adminPhone: "13672920459",
          housingInformation: null,
          memberList: null,
          area: null,
          areaText: null,
          allRoomNumbers: "10栋/1、13栋/1301-1、13栋/1301-2、2栋/1001、2栋/1002、5栋/309、88栋/1、CE栋/1208、DD栋/回归数据2、DD栋/回归数据3、DD栋/回归新数据1、K2栋/1003、K2栋/1006、K2栋/1007、S栋/2009、S栋/2010、S栋/2011、S栋/2012、S栋/808、测试租赁/101",
        },
        {
          id: "1753674949324824577",
          name: "阿里巴巴达摩院（杭州）科技有限公司",
          creditCode: "91330110MA2AXY0E7F",
          typeId: null,
          typeName: null,
          postalCode: null,
          profile: null,
          logo: null,
          logoUrl: null,
          creditUrl: null,
          contacts: "567",
          contactsPhone: null,
          contactsFax: null,
          registerDate: null,
          registerCapital: null,
          corpType: null,
          corpTypeName: null,
          provinceName: null,
          cityName: null,
          countiesName: null,
          provinceCode: null,
          cityCode: null,
          countiesCode: null,
          addr: null,
          legalPerson: null,
          legalPhone: null,
          remark: null,
          status: 0,
          customerTagline: null,
          customerUrl: null,
          email: null,
          product: null,
          deptId: "100",
          createUserId: "1717016875626741760",
          createDate: "2024-02-03 15:01:04",
          updateUserId: "1737780523903516672",
          updateDate: "2024-02-03 15:24:42",
          isDeleted: 0,
          statusStr: "正常",
          isExpired: true,
          rentalRoomNumbers: "DD栋/2001、DD栋/2002、DD栋/2003",
          purchaseRoomNumbers: null,
          rentalRoomIds: "1753673859984384001,1753673859992772609,1753673859996966913",
          purchaseRoomIds: null,
          totalContractCount: 0,
          expiredContractCount: 0,
          areaList: null,
          allAddress: null,
          contractStatus: null,
          contractStatusStr: null,
          updateUser: "jiaec02",
          settledType: "0",
          settledTypeStr: "租户",
          memberCount: 1,
          adminPhone: "13711798767",
          housingInformation: null,
          memberList: null,
          area: null,
          areaText: null,
          allRoomNumbers: "DD栋/2001、DD栋/2002、DD栋/2003",
        },
        {
          id: "1753339263912509442",
          name: "爱博诺德（北京）医疗科技股份有限公司",
          creditCode: "9111011455135477XA",
          typeId: "0",
          typeName: "独资",
          postalCode: "4444",
          profile: "继续进行jzmzms",
          logo: null,
          logoUrl: "",
          creditUrl: null,
          contacts: "44",
          contactsPhone: "13200000044",
          contactsFax: null,
          registerDate: null,
          registerCapital: null,
          corpType: null,
          corpTypeName: null,
          provinceName: "河北省",
          cityName: "秦皇岛市",
          countiesName: "北戴河区",
          provinceCode: "130000",
          cityCode: "130300",
          countiesCode: "130304",
          addr: "测试",
          legalPerson: "解江冰",
          legalPhone: null,
          remark: null,
          status: 0,
          customerTagline: "浮夸kfk",
          customerUrl: "就放假放假",
          email: null,
          product: null,
          deptId: "101",
          createUserId: "1717016875626741760",
          createDate: "2024-02-02 16:47:11",
          updateUserId: "1737780523903516672",
          updateDate: "2024-02-03 14:48:04",
          isDeleted: 0,
          statusStr: "正常",
          isExpired: false,
          rentalRoomNumbers: "S栋/2006、S栋/2007、S栋/2008",
          purchaseRoomNumbers: "S栋/901",
          rentalRoomIds: "1752594532068753410,1752594532068753411,1752594532072947713",
          purchaseRoomIds: "1752592340679131138",
          totalContractCount: 1,
          expiredContractCount: 0,
          areaList: null,
          allAddress: null,
          contractStatus: null,
          contractStatusStr: null,
          updateUser: "jiaec02",
          settledType: "1",
          settledTypeStr: "业主",
          memberCount: 1,
          adminPhone: "18666110722",
          housingInformation: null,
          memberList: null,
          area: null,
          areaText: null,
          allRoomNumbers: "S栋/901、S栋/2006、S栋/2007、S栋/2008",
        },
        {
          id: "1747467722482032642",
          name: "中国有色集团（广西）平桂飞碟股份有限公司",
          creditCode: "91451100745132489E",
          typeId: null,
          typeName: null,
          postalCode: null,
          profile: null,
          logo: null,
          logoUrl: null,
          creditUrl: null,
          contacts: "55",
          contactsPhone: null,
          contactsFax: null,
          registerDate: null,
          registerCapital: null,
          corpType: null,
          corpTypeName: null,
          provinceName: null,
          cityName: null,
          countiesName: null,
          provinceCode: null,
          cityCode: null,
          countiesCode: null,
          addr: null,
          legalPerson: null,
          legalPhone: null,
          remark: null,
          status: 0,
          customerTagline: null,
          customerUrl: null,
          email: null,
          product: null,
          deptId: "100",
          createUserId: "1717016875626741760",
          createDate: "2024-01-17 11:55:46",
          updateUserId: "1717016875626741760",
          updateDate: "2024-02-01 17:12:54",
          isDeleted: 0,
          statusStr: "正常",
          isExpired: true,
          rentalRoomNumbers: "A22栋/501、A22栋/606、S栋/2003、S栋/2004、S栋/2005",
          purchaseRoomNumbers: null,
          rentalRoomIds: "1747458530912280578,1747460928598745089,1752594532039393282,1752594532051976194,1752594532060364801",
          purchaseRoomIds: null,
          totalContractCount: 0,
          expiredContractCount: 0,
          areaList: null,
          allAddress: null,
          contractStatus: null,
          contractStatusStr: null,
          updateUser: "jiaec-陈",
          settledType: "0",
          settledTypeStr: "租户",
          memberCount: 0,
          adminPhone: null,
          housingInformation: null,
          memberList: null,
          area: null,
          areaText: null,
          allRoomNumbers: "A22栋/501、A22栋/606、S栋/2003、S栋/2004、S栋/2005",
        },
        {
          id: "1748618670118133761",
          name: "浙江正元智慧科技股份有限公司",
          creditCode: "913300007200827022",
          typeId: null,
          typeName: null,
          postalCode: null,
          profile: null,
          logo: null,
          logoUrl: null,
          creditUrl: null,
          contacts: "222",
          contactsPhone: null,
          contactsFax: null,
          registerDate: null,
          registerCapital: null,
          corpType: null,
          corpTypeName: null,
          provinceName: null,
          cityName: null,
          countiesName: null,
          provinceCode: null,
          cityCode: null,
          countiesCode: null,
          addr: null,
          legalPerson: null,
          legalPhone: null,
          remark: null,
          status: 0,
          customerTagline: null,
          customerUrl: null,
          email: null,
          product: null,
          deptId: "100",
          createUserId: "1713810063830630400",
          createDate: "2024-01-20 16:09:13",
          updateUserId: "1713810063830630400",
          updateDate: "2024-02-01 16:15:34",
          isDeleted: 0,
          statusStr: "正常",
          isExpired: true,
          rentalRoomNumbers: "A22栋/501、A22栋/606、CE栋/901",
          purchaseRoomNumbers: null,
          rentalRoomIds: "1747458530912280578,1747460928598745089,1748291936755675138",
          purchaseRoomIds: null,
          totalContractCount: 0,
          expiredContractCount: 0,
          areaList: null,
          allAddress: null,
          contractStatus: null,
          contractStatusStr: null,
          updateUser: "zhouyp",
          settledType: "0",
          settledTypeStr: "租户",
          memberCount: 0,
          adminPhone: null,
          housingInformation: null,
          memberList: null,
          area: null,
          areaText: null,
          allRoomNumbers: "A22栋/501、A22栋/606、CE栋/901",
        },
        {
          id: "1752966602346827778",
          name: "帝信科技股份有限公司",
          creditCode: "912101007111137222",
          typeId: null,
          typeName: null,
          postalCode: null,
          profile: null,
          logo: null,
          logoUrl: null,
          creditUrl: null,
          contacts: "222",
          contactsPhone: null,
          contactsFax: null,
          registerDate: null,
          registerCapital: null,
          corpType: null,
          corpTypeName: null,
          provinceName: null,
          cityName: null,
          countiesName: null,
          provinceCode: null,
          cityCode: null,
          countiesCode: null,
          addr: null,
          legalPerson: null,
          legalPhone: null,
          remark: null,
          status: 0,
          customerTagline: null,
          customerUrl: null,
          email: null,
          product: null,
          deptId: "100",
          createUserId: "1713810063830630400",
          createDate: "2024-02-01 16:06:21",
          updateUserId: "1713810063830630400",
          updateDate: "2024-02-01 16:06:21",
          isDeleted: 0,
          statusStr: "正常",
          isExpired: true,
          rentalRoomNumbers: "CE栋/901",
          purchaseRoomNumbers: null,
          rentalRoomIds: "1748291936755675138",
          purchaseRoomIds: null,
          totalContractCount: 0,
          expiredContractCount: 0,
          areaList: null,
          allAddress: null,
          contractStatus: null,
          contractStatusStr: null,
          updateUser: "zhouyp",
          settledType: "0",
          settledTypeStr: "租户",
          memberCount: 0,
          adminPhone: null,
          housingInformation: null,
          memberList: null,
          area: null,
          areaText: null,
          allRoomNumbers: "CE栋/901",
        },
        {
          id: "1751815420530159617",
          name: "新疆交通科学研究院有限责任公司",
          creditCode: "9165000045760113XW",
          typeId: null,
          typeName: null,
          postalCode: null,
          profile: null,
          logo: null,
          logoUrl: null,
          creditUrl: null,
          contacts: "承租人6",
          contactsPhone: null,
          contactsFax: null,
          registerDate: null,
          registerCapital: null,
          corpType: null,
          corpTypeName: null,
          provinceName: null,
          cityName: null,
          countiesName: null,
          provinceCode: null,
          cityCode: null,
          countiesCode: null,
          addr: null,
          legalPerson: null,
          legalPhone: null,
          remark: null,
          status: 0,
          customerTagline: null,
          customerUrl: null,
          email: null,
          product: null,
          deptId: "100",
          createUserId: "1717016875626741760",
          createDate: "2024-01-29 11:51:58",
          updateUserId: "1717016875626741760",
          updateDate: "2024-01-30 11:28:06",
          isDeleted: 0,
          statusStr: "正常",
          isExpired: true,
          rentalRoomNumbers: "78栋/501、78栋/601、78栋/701",
          purchaseRoomNumbers: null,
          rentalRoomIds: "1751790795788152834,1751790927384440834,1751854508855554049",
          purchaseRoomIds: null,
          totalContractCount: 0,
          expiredContractCount: 0,
          areaList: null,
          allAddress: null,
          contractStatus: null,
          contractStatusStr: null,
          updateUser: "jiaec-陈",
          settledType: "0",
          settledTypeStr: "租户",
          memberCount: 1,
          adminPhone: "18666135203",
          housingInformation: null,
          memberList: null,
          area: null,
          areaText: null,
          allRoomNumbers: "78栋/501、78栋/601、78栋/701",
        },
        {
          id: "1752163182228566017",
          name: "温州哈哈哈哈品牌管理有限公司",
          creditCode: "91330302MAC93M8L6Q",
          typeId: null,
          typeName: null,
          postalCode: "519000",
          profile: null,
          logo: null,
          logoUrl: null,
          creditUrl: null,
          contacts: "1111",
          contactsPhone: "11111",
          contactsFax: null,
          registerDate: null,
          registerCapital: null,
          corpType: null,
          corpTypeName: null,
          provinceName: "北京市",
          cityName: "市辖区",
          countiesName: "东城区",
          provinceCode: "110000",
          cityCode: "110100",
          countiesCode: "110101",
          addr: "Zhuhai, Guangdong, China",
          legalPerson: "钱品益",
          legalPhone: null,
          remark: null,
          status: 0,
          customerTagline: null,
          customerUrl: null,
          email: null,
          product: null,
          deptId: "100",
          createUserId: "1717095443921141760",
          createDate: "2024-01-30 10:53:51",
          updateUserId: "1717095443921141760",
          updateDate: "2024-01-30 10:53:51",
          isDeleted: 0,
          statusStr: "正常",
          isExpired: false,
          rentalRoomNumbers: null,
          purchaseRoomNumbers: "A栋/122",
          rentalRoomIds: null,
          purchaseRoomIds: "1752162820226576385",
          totalContractCount: 1,
          expiredContractCount: 0,
          areaList: null,
          allAddress: null,
          contractStatus: null,
          contractStatusStr: null,
          updateUser: "liujiale",
          settledType: "1",
          settledTypeStr: "业主",
          memberCount: 0,
          adminPhone: null,
          housingInformation: null,
          memberList: null,
          area: null,
          areaText: null,
          allRoomNumbers: "A栋/122",
        },
        {
          id: "1719650470785536002",
          name: "广州智云智能科技有限公司",
          creditCode: "91440112070152448A",
          typeId: "2",
          typeName: "国有",
          postalCode: "519100",
          profile: "爱国之士",
          logo: null,
          logoUrl: "",
          creditUrl: null,
          contacts: "大苹果",
          contactsPhone: "13229471384",
          contactsFax: null,
          registerDate: null,
          registerCapital: null,
          corpType: null,
          corpTypeName: null,
          provinceName: "天津市",
          cityName: "市辖区",
          countiesName: "河东区",
          provinceCode: "120000",
          cityCode: "120100",
          countiesCode: "120102",
          addr: null,
          legalPerson: "李寒峰",
          legalPhone: null,
          remark: null,
          status: 0,
          customerTagline: "1",
          customerUrl: "1556",
          email: "1222",
          product: "11",
          deptId: "103",
          createUserId: "1713810063830630400",
          createDate: "2023-11-01 17:39:56",
          updateUserId: "1748239418958553088",
          updateDate: "2024-01-29 10:20:27",
          isDeleted: 0,
          statusStr: "正常",
          isExpired: true,
          rentalRoomNumbers: null,
          purchaseRoomNumbers: null,
          rentalRoomIds: null,
          purchaseRoomIds: null,
          totalContractCount: 1,
          expiredContractCount: 1,
          areaList: null,
          allAddress: null,
          contractStatus: null,
          contractStatusStr: null,
          updateUser: "梁咏茵09",
          settledType: null,
          settledTypeStr: "——",
          memberCount: 1,
          adminPhone: "18666136583",
          housingInformation: null,
          memberList: null,
          area: null,
          areaText: null,
          allRoomNumbers: "——",
        },
      ],
    }
  },
  mounted() {
    window.onresize = () => {
      this.resetTableHeight()
    }
    this.resetTableHeight()
    this.initSearch()
  },
  methods: {
    /**
     * 修改搜索栏展示状态
     */
    changeSearchStatus() {
      this.show = !this.show
      this.resetTableHeight()
    },
    /**
     * 更新表格高度
     */
    resetTableHeight() {
      this.$nextTick(() => {
        let height = this.$refs.table.$el.offsetHeight
        this.tableHeight = height
        this.$forceUpdate()
      })
    },
    /**
     * 初始化搜索信息
     */
    initSearch() {
      const nodes = this.$slots.default
      const searchConfig = []
      for (let index = 0; index < nodes.length; index++) {
        const node = nodes[index]
        const component = node.componentInstance
        if (component.search != true) {
          //如果不是搜索字段
          continue
        }
        // seApi: undefined
        // seNimble: false
        // seMultiple: false
        // seParams: undefined
        // seProp: undefined
        // seType: "input"
        // search: false
        const params = {
          api: component.seApi,
          nimble: component.seNimble,
          multiple: component.seMultiple,
          params: component.seParams,
          prop: component.seProp ?? component.prop,
          label: component.seLabel ?? component.label,
          type: component.seType,
          options: component.seOptions,
          placeholder: component.sePlaceholder ?? component.label,
        }
        searchConfig.push(params)
      }
      this.searchConfig = searchConfig
    },
    /**
     * 刷新列表
     * @param {是否重置页码} resetPage
     */
    refresh(resetPage = false) {},
  },
}
</script>

<style>
.me-table {
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
}
.me-table-tool {
  display: flex;
  flex-direction: row;
  width: 100%;
  padding: 10px 0;
  justify-content: space-between;
}
.me-table-footer {
  padding: 21px 0;
  border-top: 1px solid #ebeef5;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}
</style>
